controller:
  metrics:
    enabled: true
  service:
    externalTrafficPolicy: "Local"
    annotations:
      # AWS Load Balancer Controller Annotations
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:680080015686:certificate/83180aa0-1d61-40de-9a7f-26970c20161a
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-type: 'external'
      service.beta.kubernetes.io/aws-load-balancer-scheme: 'internet-facing'
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: 'ip'
      prometheus.io/port: '10254'
      prometheus.io/scrape: true
    targetPorts:
      https: http