apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-app
spec:
  selector:
    matchLabels:
      app: comments-app
  replicas: 2
  template:
    metadata:
      labels:
        app: comments-app
    spec:
      containers:
      - name: comments-app
        image: ECR_IMAGE
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "256m"
          limits: 
            memory: "256Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /api/comment/list/1
            port: 5000
          periodSeconds: 4
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /api/comment/list/1
            port: 5000
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /api/comment/list/1
            port: 5000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
